### PR TITLE
Staging env fallback for tests

### LINKED ISSUE #90: Projects without a staging environment fail on CI/CD
Due to lack of testing on projects without a staging environment setup, CI/CD tests fail when `preview:staging` is called. Tests should point to `preview:production` server when no Staging environment is setup.

### PR DESCRIPTION
**Pull request by rioam2**
Resolves #90

### CODE REVIEW

File: scripts/loadenv.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ const { exec } = require('child_process');
 const mergedEnv = { ...dotenv.parsed, ...process.env };
 const command = process.argv
 	.slice(2)
+	.map((arg) => (arg.includes(' ') && `'${arg}'`) || arg)
```
Comment (rioam2) [inline scripts/loadenv.js]: Needed as multi-word arguments with quotes are passed into node as a single array element with a space in between. The existence of a space means the argument needs to be re-quoted.

May have some adverse side-effects based on if the argument actually contains its own single quotes...

File: scripts/test.sh [hunk 2]
```diff
@@ -2,16 +2,18 @@
...
-    
-    # Continuous Deployment for staging/production
-    if [[ $TRAVIS_BRANCH == 'master' ]]; then
-        if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
+yarn test
+
+# Continuous Deployment for staging/production
+if [[ $TRAVIS_BRANCH == 'master' ]]; then
+    if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
+        if [[ ! -z $STATIC_PROD_PROJECT ]] && [[ ! -z $STATIC_DEPLOY_KEY ]]; then
```
Comment (rioam2) [inline scripts/test.sh]: These checks are more granular and therefore preferred over the general `$TRAVIS_SECURE_ENV_VARS` check removed above.

File: package.json [hunk 3]
```diff
@@ -19,7 +19,7 @@
 		"preview:staging": "cross-env NODE_ENV=production yarn loadenv ./scripts/preview.sh",
 		"setup": "./scripts/setup.js",
 		"test": "yarn test:unit && yarn test:cypress",
-		"test:cypress": "start-server-and-test 'yarn preview:staging > /dev/null' 3000 'cypress run'",
+		"test:cypress": "yarn loadenv yarn start-server-and-test '[ -z %STATIC_STAGE_PROJECT ] && yarn preview:production > /dev/null || yarn preview:staging > /dev/null' 3000 'cypress run'",
```
Comment (rioam2) [inline package.json]: This script is a little messy right now. May be best to migrate into `scripts/` as a separate file later on...
